name: awesome_input
description: This is a custom input package having multiple input types
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies:
  build_runner:
  flutter_gen_runner:


flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/drawables/
    - assets/icons/
    

library:
  name: lib/awesome_input.dart
